// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: handler/grpc/proto/card.proto

package service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PingRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRq) Reset() {
	*x = PingRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_grpc_proto_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRq) ProtoMessage() {}

func (x *PingRq) ProtoReflect() protoreflect.Message {
	mi := &file_handler_grpc_proto_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRq.ProtoReflect.Descriptor instead.
func (*PingRq) Descriptor() ([]byte, []int) {
	return file_handler_grpc_proto_card_proto_rawDescGZIP(), []int{0}
}

func (x *PingRq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode string `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
}

func (x *PingRp) Reset() {
	*x = PingRp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_grpc_proto_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRp) ProtoMessage() {}

func (x *PingRp) ProtoReflect() protoreflect.Message {
	mi := &file_handler_grpc_proto_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRp.ProtoReflect.Descriptor instead.
func (*PingRp) Descriptor() ([]byte, []int) {
	return file_handler_grpc_proto_card_proto_rawDescGZIP(), []int{1}
}

func (x *PingRp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

var File_handler_grpc_proto_card_proto protoreflect.FileDescriptor

var file_handler_grpc_proto_card_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x06, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x06,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x39, 0x0a, 0x0b, 0x43, 0x61,
	0x72, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x71, 0x1a, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_handler_grpc_proto_card_proto_rawDescOnce sync.Once
	file_handler_grpc_proto_card_proto_rawDescData = file_handler_grpc_proto_card_proto_rawDesc
)

func file_handler_grpc_proto_card_proto_rawDescGZIP() []byte {
	file_handler_grpc_proto_card_proto_rawDescOnce.Do(func() {
		file_handler_grpc_proto_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_handler_grpc_proto_card_proto_rawDescData)
	})
	return file_handler_grpc_proto_card_proto_rawDescData
}

var file_handler_grpc_proto_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_handler_grpc_proto_card_proto_goTypes = []interface{}{
	(*PingRq)(nil), // 0: service.PingRq
	(*PingRp)(nil), // 1: service.PingRp
}
var file_handler_grpc_proto_card_proto_depIdxs = []int32{
	0, // 0: service.CardHandler.Ping:input_type -> service.PingRq
	1, // 1: service.CardHandler.Ping:output_type -> service.PingRp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_handler_grpc_proto_card_proto_init() }
func file_handler_grpc_proto_card_proto_init() {
	if File_handler_grpc_proto_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_handler_grpc_proto_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_grpc_proto_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handler_grpc_proto_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_handler_grpc_proto_card_proto_goTypes,
		DependencyIndexes: file_handler_grpc_proto_card_proto_depIdxs,
		MessageInfos:      file_handler_grpc_proto_card_proto_msgTypes,
	}.Build()
	File_handler_grpc_proto_card_proto = out.File
	file_handler_grpc_proto_card_proto_rawDesc = nil
	file_handler_grpc_proto_card_proto_goTypes = nil
	file_handler_grpc_proto_card_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CardHandlerClient is the client API for CardHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardHandlerClient interface {
	Ping(ctx context.Context, in *PingRq, opts ...grpc.CallOption) (*PingRp, error)
}

type cardHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCardHandlerClient(cc grpc.ClientConnInterface) CardHandlerClient {
	return &cardHandlerClient{cc}
}

func (c *cardHandlerClient) Ping(ctx context.Context, in *PingRq, opts ...grpc.CallOption) (*PingRp, error) {
	out := new(PingRp)
	err := c.cc.Invoke(ctx, "/service.CardHandler/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardHandlerServer is the server API for CardHandler service.
type CardHandlerServer interface {
	Ping(context.Context, *PingRq) (*PingRp, error)
}

// UnimplementedCardHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedCardHandlerServer struct {
}

func (*UnimplementedCardHandlerServer) Ping(context.Context, *PingRq) (*PingRp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterCardHandlerServer(s *grpc.Server, srv CardHandlerServer) {
	s.RegisterService(&_CardHandler_serviceDesc, srv)
}

func _CardHandler_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardHandlerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CardHandler/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardHandlerServer).Ping(ctx, req.(*PingRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.CardHandler",
	HandlerType: (*CardHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CardHandler_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler/grpc/proto/card.proto",
}
